services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

  ml_service:
    build:
      context: .
      dockerfile: ml_service/Dockerfile
    ports:
      - "8001:8001"

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    environment:
      VITE_ML_SERVICE_URL: http://localhost:8001
    depends_on:
      - backend
      - ml_service
    ports:
      - "5173:5173"

  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --url http://frontend:5173
    depends_on:
      - frontend
