services:
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "5173:5173"

  tunnel:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate --url http://frontend:5173
    depends_on:
      - frontend
